[peripherals.cordic]
ident = "cordic"
base_addr = 1073875968
entitlements = []

[peripherals.cordic.registers.csr]
ident = "csr"
offset = 0

[peripherals.cordic.registers.csr.fields.func]
ident = "func"
offset = 0
width = 4

[peripherals.cordic.registers.csr.fields.func.numericity.Enumerated.variants.cos]
ident = "cos"
bits = 0
