[peripherals.CORDIC]
ident = "CORDIC"
base_addr = 1073875968
entitlements = []

[peripherals.CORDIC.registers]

[peripherals.USART1]
ident = "USART1"
base_addr = 1073821696
entitlements = []

[peripherals.USART1.registers]

[peripherals.RCC]
ident = "RCC"
base_addr = 1073876992
entitlements = []

[peripherals.RCC.registers]

[peripherals.GPIO]
ident = "GPIO"
base_addr = 1207959552
entitlements = []

[peripherals.GPIO.registers]

[peripherals.SYSCFG]
ident = "SYSCFG"
base_addr = 1073807360
entitlements = []

[peripherals.SYSCFG.registers]
