[package]
name = "ir"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
Inflector = "0.11.4"
proc-macro2 = "1.0.89"
quote = "1.0.37"
tiva = "0.3.0"
syn = { version = "2.0.87", features = ["full"] }
ters = "0.1.0"
prettyplease = "0.2.32"
log = "0.4.27"
